public enum TypePanel
{
    Player,
    PlayerWithEnemy,
    Do,
    Move,
    MoveRun,
    RoomName,
    Blackout,
    Inventory,
    WinItems,
    InfoAboutItem,
    InfoAfterPlayerCircle,
    InfoEnemyAction,
    Settings,
    CharacterSay,
    TrainerSay,
    PointParameter,
    BlackoutOverAll,
    MainMenu,
    MoreInfo,
    Quests
}
